name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master] # Триггер на push в эти ветки

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Export static site
      run: npm run export
      
    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        enable_jekyll: false